# Generated by Django 4.2.5 on 2023-09-28 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_user_id(apps, schema_editor):
    UserProfileAccount = apps.get_model('accounts', 'UserProfileAccount')
    User = apps.get_model('auth', 'User')

    # Loop through UserProfileAccount instances and set user_id based on the 'user' relationship
    for profile in UserProfileAccount.objects.all():
        profile.user_id = profile.user.id
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_useraccount_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileaccount",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
