# Generated by Django 4.2.5 on 2023-09-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofileaccount_user"),
    ]

    operations = []
